# DB properties:
spring:
  data:
    rest:
      base-path: /images
  datasource:
    url: jdbc:h2:mem:image_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
            generate_statistics: true
            show_sql: true
            use_sql_comments: true
            format_sql: true
  application:
    name: image.api
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  error:
    whitelabel:
      enabled: true
  port: 8090



